#!/bin/bash
set -ex

sudo apk add --no-cache \
	build-base clang clang-dev libelf \
	zlib linux-tools elfutils-dev linux-headers \
	libc-dev llvm16 python3 py3-pip iproute2

export PATH=/usr/lib/llvm16/bin:$PATH
echo 'export PATH=/usr/lib/llvm16/bin:$PATH' >> ~/.zshrc

scripts/install-bpftool
scripts/install-libbpf

sudo mount -t debugfs none /sys/kernel/debug

python3 -m venv .venv