name: build

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make test
          push: never
        env:
          VERSION: ${{ github.ref_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/knock

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make build
          push: never
        env:
          VERSION: ${{ github.ref_name }}

      - name: Rename binary with architecture
        run: |
          ARCH=$(uname -m)
          mv build/knock build/knock-$ARCH

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          draft: true
          files: build/knock-*
